### ISSUE TITLE
build failure FC12 AMD64

### ISSUE THREAD

**Issue by ehedgehog** [zot/go-fltk#2]
cloned the repository (a few minutes ago, 22Nov2010 13:20ish), did a `make install`. Make downloads fltk and starts compiling. All is well until:

g++ -Ifltk-2.0.x-r7725 -c fltk.cxx
g++ -m64 -o cgo_fltk.so fltk.cgo2.o widget.cgo2.o group.cgo2.o input.cgo2.o texteditor.cgo2.o window.cgo2.o fltk.o fltk-2.0.x-r7725/lib/libfltk2.a -lXext -lXinerama -lXft -lX11 -lXi -lm  -shared -lpthread -lm
/usr/bin/ld: fltk.o: relocation R_X86_64_32 against `typeinfo for EventStealer' can not be used when making a shared object; recompile with -fPIC
fltk.o: could not read symbols: Bad value
collect2: ld returned 1 exit status

Happy to try recompiling with -fPIC if someone can tell me where/how to add it.

Running Fedora Core 12, system update as of this morning, on an AMD64-style system.

uname -a output:

Linux chris.pseudo-epimorphics.com 2.6.32.23-170.fc12.x86_64 #1 SMP Mon Sep 27 17:23:59 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

Chris

**Comment by ehedgehog** [comment]
PS "all is well" excludes various warnings eg

x11/run.cxx:1969: warning: dereferencing pointer 'me' does break strict-aliasing rules'

TextBuffer.cxx: In member function 'char\* fltk::TextBuffer::selection_text_(fltk::TextSelection*)':
TextBuffer.cxx:1802: warning: 'rectstart' may be used uninitialized in this function

I'll present the whole lot if it's seemed relevant.

Chris

**Comment by zot** [comment]
Sorry, I didn't see this comment earlier.  It looks like the fltk.o it's referring to is from my fltk.cxx file and produced by the fltk.o rule in the Makefile.  You can try adding -fPIC there and see if that works.
